services:
  yes-no-search:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/yes-no-search"
      - "/opt/yes-no-search/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true